In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

We need to create a folder for each year, 2000 -> 2020, with unique load_data.csv and generator_variability.csv files for each

In [ ]:
years = np.arange(2000, 2021)

In [2]:
long_data_dir = Path.cwd().joinpath('data')
long_load = pd.read_csv(long_data_dir.joinpath('Load_data.csv'), index_col=0)
long_variability = pd.read_csv(long_data_dir.joinpath('Generators_variability.csv'), index_col=0)

In [3]:
long_load

,Demand_Segment,Cost_of_Demand_Curtailment_per_MW,Max_Demand_Curtailment,Rep_Periods,Timesteps_per_Rep_Period,Sub_Weights,Time_Index,Load_MW_z1,Load_MW_z2,Load_MW_z3,Load_MW_z4,Load_MW_z5,Load_MW_z6,Load_MW_z7
Voll,,,,,,,,,,,,,,
50000.0,1.0,1.0,1.0,1.0,175200.0,1.0,1,26065.8,3652.196447,2324.919779,1655.254882,7067.857344,2436.675986,4444.086944
NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,25944.3,3484.754690,2181.902126,1567.857211,6424.327847,2347.231104,4074.101539
NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,25414.1,3467.618248,2136.644889,1545.267752,6144.778214,2338.653483,3922.335762
NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,25271.4,3454.546043,2102.900201,1499.724664,5910.391152,2320.344322,3837.099291
NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,25413.1,3535.871531,2111.324682,1516.352696,5719.658560,2366.900649,3794.546140
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
NaN,NaN,NaN,NaN,NaN,NaN,NaN,175196,33257.2,4550.483727,3234.951992,2114.448837,11368.553800,3008.945061,6858.344253
NaN,NaN,NaN,NaN,NaN,NaN,NaN,175197,32202.7,4411.695062,3089.132952,2030.112033,10751.674320,2910.028683,6613.401190
NaN,NaN,NaN,NaN,NaN,NaN,NaN,175198,31362.1,4247.013647,2923.715494,1936.506534,10094.591670,2854.576868,6268.101835
NaN,NaN,NaN,NaN,NaN,NaN,NaN,175199,30462.8,4077.831959,2780.129929,1851.157001,9374.853999,2699.608649,5841.600152
NaN,NaN,NaN,NaN,NaN,NaN,NaN,175200,29275.7,3059.960536,2171.217572,1439.619581,8026.500143,1906.082317,4833.288223

In [ ]:
for year in [2000]:
    # Create